--DROP TABLE IF EXISTS film_likes;
--DROP TABLE IF EXISTS friends;
--DROP TABLE IF EXISTS USERS;
--DROP TABLE IF EXISTS GENRE;
--DROP TABLE IF EXISTS GENRES;
--DROP TABLE IF EXISTS FILMS;
--DROP TABLE IF EXISTS MPA_RATING;


CREATE TABLE IF NOT EXISTS mpa_rating(
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films(
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(200) NOT NULL,
description VARCHAR(200) NOT NULL,
release_date DATE NOT NULL,
duration INTEGER NOT NULL,
mpa_rating_id INTEGER REFERENCES mpa_rating (id) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres(
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre(
film_id INTEGER REFERENCES films (id) NOT NULL,
genre_id INTEGER REFERENCES genres (id) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
email VARCHAR(50) UNIQUE NOT NULL,
login VARCHAR(50) UNIQUE NOT NULL,
name VARCHAR(50) NOT NULL,
birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS friends(
user_id INTEGER REFERENCES users(id),
to_user_id INTEGER REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS film_likes (
film_id INTEGER REFERENCES films (id),
user_id INTEGER REFERENCES users (id)
);